name: CI

on:
  workflow_dispatch:
  push:
  pull_request:

permissions: {}

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Run pre-commit
        uses: tox-dev/action-pre-commit-uv@v1
